# Generated by Django 3.0.5 on 2020-04-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='user_book')),
            ],
            options={
                'verbose_name': 'AddBook',
                'verbose_name_plural': 'AddBooks',
            },
        ),
    ]
