# Generated by Django 3.0.5 on 2020-04-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200423_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_book/'),
        ),
        migrations.AlterField(
            model_name='addbook',
            name='title',
            field=models.CharField(max_length=240),
        ),
    ]
