# Generated by Django 3.0.5 on 2020-04-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200423_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=80)),
                ('was_born', models.DateField()),
                ('was_died', models.DateField()),
                ('photo', models.ImageField(blank=True, upload_to='author_book/')),
                ('author_book', models.ManyToManyField(to='catalog.AddBook')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
    ]
