# Generated by Django 3.0.5 on 2020-04-24 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_book',
            new_name='book',
        ),
    ]
