# Generated by Django 3.0.5 on 2020-04-24 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200424_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='was_died',
        ),
    ]
