# Generated by Django 3.0.5 on 2020-04-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_author_was_died'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
