# Generated by Django 3.0.5 on 2020-04-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_addbook_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='slug',
            field=models.SlugField(default='', max_length=150, unique=True),
        ),
    ]
