# Generated by Django 3.0.5 on 2020-04-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200424_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='slug',
            field=models.SlugField(default='book', max_length=150, unique=True),
        ),
    ]
