# Generated by Django 3.0.5 on 2020-04-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_addbook_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='slug',
            field=models.SlugField(max_length=130, null=True, unique=True),
        ),
    ]
