# Generated by Django 3.0.5 on 2020-04-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_addbook_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='slug',
            field=models.SlugField(default='FEDORA', max_length=130, unique=True),
        ),
    ]
