# Generated by Django 3.0.7 on 2020-06-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_addbook_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='file_book',
            field=models.FileField(null=True, upload_to='file_book'),
        ),
    ]
